/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cattle {
  'id' : bigint,
  'purchasePrice' : number,
  'dateOfPurchase' : bigint,
  'healthStatus' : HealthStatus,
  'availability' : CattleAvailability,
  'breed' : string,
  'tagNumber' : string,
}
export type CattleAvailability = { 'Available' : null } |
  { 'Reserved' : null } |
  { 'Sold' : null };
export interface CattleOrder {
  'status' : OrderStatus,
  'deliveryNotes' : string,
  'orderDate' : bigint,
  'orderId' : bigint,
  'cattleTagNumber' : string,
  'customerId' : bigint,
}
export interface CustomerAccount {
  'id' : bigint,
  'username' : string,
  'name' : string,
  'isActive' : boolean,
  'address' : string,
  'passwordHash' : string,
  'phone' : string,
}
export type HealthStatus = { 'Healthy' : null } |
  { 'Sick' : null } |
  { 'Recovered' : null };
export interface InventoryItem {
  'id' : bigint,
  'lowStockThreshold' : number,
  'name' : string,
  'unit' : string,
  'addedBy' : Principal,
  'notes' : string,
  'quantity' : number,
  'category' : string,
}
export interface InventoryStat {
  'uniqueCattleCount' : bigint,
  'avgDailyProduction' : number,
  'totalRecords' : bigint,
  'totalQuantity' : number,
}
export interface InventoryStats {
  'categoryCount' : bigint,
  'lowStockItems' : bigint,
  'totalItems' : bigint,
}
export interface MilkProductionRecord {
  'id' : bigint,
  'date' : bigint,
  'quantityLiters' : number,
  'addedBy' : Principal,
  'notes' : string,
  'cattleTag' : string,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'OutForDelivery' : null } |
  { 'Pending' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCattle' : ActorMethod<
    [string, string, bigint, number, CattleAvailability, HealthStatus],
    undefined
  >,
  'addCustomer' : ActorMethod<
    [string, string, string, string, string, boolean],
    undefined
  >,
  'addInventoryItem' : ActorMethod<
    [string, string, number, string, number, string],
    undefined
  >,
  'addMilkProductionRecord' : ActorMethod<
    [string, number, bigint, string],
    undefined
  >,
  'adminLogin' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCattle' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteInventoryItem' : ActorMethod<[bigint], undefined>,
  'deleteMilkProductionRecord' : ActorMethod<[bigint], undefined>,
  'getAllCattle' : ActorMethod<[], Array<Cattle>>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerAccount>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllMilkProductionRecords' : ActorMethod<[], Array<MilkProductionRecord>>,
  'getAllOrders' : ActorMethod<[], Array<CattleOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventoryStats' : ActorMethod<[], InventoryStats>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getMilkProductionStats' : ActorMethod<[], InventoryStat>,
  'getMyOrders' : ActorMethod<[], Array<CattleOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkCustomerPrincipal' : ActorMethod<[bigint, Principal], undefined>,
  'placeOrder' : ActorMethod<[bigint, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomerActive' : ActorMethod<[bigint, boolean], undefined>,
  'updateCattle' : ActorMethod<
    [bigint, string, string, bigint, number, CattleAvailability, HealthStatus],
    undefined
  >,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    undefined
  >,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, string, number, string, number, string],
    undefined
  >,
  'updateMilkProductionRecord' : ActorMethod<
    [bigint, string, number, bigint, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];