/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CattleAvailability = IDL.Variant({
  'Available' : IDL.Null,
  'Reserved' : IDL.Null,
  'Sold' : IDL.Null,
});
export const HealthStatus = IDL.Variant({
  'Healthy' : IDL.Null,
  'Sick' : IDL.Null,
  'Recovered' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Cattle = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Float64,
  'dateOfPurchase' : IDL.Int,
  'healthStatus' : HealthStatus,
  'availability' : CattleAvailability,
  'breed' : IDL.Text,
  'tagNumber' : IDL.Text,
});
export const CustomerAccount = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'addedBy' : IDL.Principal,
  'notes' : IDL.Text,
  'quantity' : IDL.Float64,
  'category' : IDL.Text,
});
export const MilkProductionRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'quantityLiters' : IDL.Float64,
  'addedBy' : IDL.Principal,
  'notes' : IDL.Text,
  'cattleTag' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'OutForDelivery' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CattleOrder = IDL.Record({
  'status' : OrderStatus,
  'deliveryNotes' : IDL.Text,
  'orderDate' : IDL.Int,
  'orderId' : IDL.Nat,
  'cattleTagNumber' : IDL.Text,
  'customerId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InventoryStats = IDL.Record({
  'categoryCount' : IDL.Nat,
  'lowStockItems' : IDL.Nat,
  'totalItems' : IDL.Nat,
});
export const InventoryStat = IDL.Record({
  'uniqueCattleCount' : IDL.Nat,
  'avgDailyProduction' : IDL.Float64,
  'totalRecords' : IDL.Nat,
  'totalQuantity' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCattle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        CattleAvailability,
        HealthStatus,
      ],
      [],
      ['oneway'],
    ),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      ['oneway'],
    ),
  'addInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64, IDL.Text],
      [],
      ['oneway'],
    ),
  'addMilkProductionRecord' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Int, IDL.Text],
      [],
      ['oneway'],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCattle' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteMilkProductionRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllCattle' : IDL.Func([], [IDL.Vec(Cattle)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerAccount)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllMilkProductionRecords' : IDL.Func(
      [],
      [IDL.Vec(MilkProductionRecord)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(CattleOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventoryStats' : IDL.Func([], [InventoryStats], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getMilkProductionStats' : IDL.Func([], [InventoryStat], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(CattleOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkCustomerPrincipal' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], ['oneway']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomerActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateCattle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        CattleAvailability,
        HealthStatus,
      ],
      [],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateMilkProductionRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CattleAvailability = IDL.Variant({
    'Available' : IDL.Null,
    'Reserved' : IDL.Null,
    'Sold' : IDL.Null,
  });
  const HealthStatus = IDL.Variant({
    'Healthy' : IDL.Null,
    'Sick' : IDL.Null,
    'Recovered' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Cattle = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Float64,
    'dateOfPurchase' : IDL.Int,
    'healthStatus' : HealthStatus,
    'availability' : CattleAvailability,
    'breed' : IDL.Text,
    'tagNumber' : IDL.Text,
  });
  const CustomerAccount = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'addedBy' : IDL.Principal,
    'notes' : IDL.Text,
    'quantity' : IDL.Float64,
    'category' : IDL.Text,
  });
  const MilkProductionRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'quantityLiters' : IDL.Float64,
    'addedBy' : IDL.Principal,
    'notes' : IDL.Text,
    'cattleTag' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'OutForDelivery' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CattleOrder = IDL.Record({
    'status' : OrderStatus,
    'deliveryNotes' : IDL.Text,
    'orderDate' : IDL.Int,
    'orderId' : IDL.Nat,
    'cattleTagNumber' : IDL.Text,
    'customerId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InventoryStats = IDL.Record({
    'categoryCount' : IDL.Nat,
    'lowStockItems' : IDL.Nat,
    'totalItems' : IDL.Nat,
  });
  const InventoryStat = IDL.Record({
    'uniqueCattleCount' : IDL.Nat,
    'avgDailyProduction' : IDL.Float64,
    'totalRecords' : IDL.Nat,
    'totalQuantity' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCattle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          CattleAvailability,
          HealthStatus,
        ],
        [],
        ['oneway'],
      ),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        ['oneway'],
      ),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64, IDL.Text],
        [],
        ['oneway'],
      ),
    'addMilkProductionRecord' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Int, IDL.Text],
        [],
        ['oneway'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCattle' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteMilkProductionRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllCattle' : IDL.Func([], [IDL.Vec(Cattle)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerAccount)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllMilkProductionRecords' : IDL.Func(
        [],
        [IDL.Vec(MilkProductionRecord)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(CattleOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventoryStats' : IDL.Func([], [InventoryStats], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getMilkProductionStats' : IDL.Func([], [InventoryStat], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(CattleOrder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkCustomerPrincipal' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], ['oneway']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomerActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateCattle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          CattleAvailability,
          HealthStatus,
        ],
        [],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateMilkProductionRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };