/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'activeStatus' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DeliveryRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'missed' : IDL.Null, 'delivered' : IDL.Null }),
  'date' : Time,
  'quantityLiters' : IDL.Float64,
  'deliveryBoyName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
});
export const MilkProductionRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'quantityLiters' : IDL.Float64,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addDeliveryRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Time,
        IDL.Float64,
        IDL.Variant({ 'missed' : IDL.Null, 'delivered' : IDL.Null }),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addMilkProductionRecord' : IDL.Func(
      [Time, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getDeliveryRecordsByCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DeliveryRecord)],
      ['query'],
    ),
  'getDeliveryRecordsByDate' : IDL.Func(
      [Time],
      [IDL.Vec(DeliveryRecord)],
      ['query'],
    ),
  'getDeliveryRecordsByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DeliveryRecord)],
      ['query'],
    ),
  'getMilkProductionRecords' : IDL.Func(
      [],
      [IDL.Vec(MilkProductionRecord)],
      ['query'],
    ),
  'getMilkRecordsByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(MilkProductionRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'activeStatus' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DeliveryRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'missed' : IDL.Null, 'delivered' : IDL.Null }),
    'date' : Time,
    'quantityLiters' : IDL.Float64,
    'deliveryBoyName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
  });
  const MilkProductionRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'quantityLiters' : IDL.Float64,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addDeliveryRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Time,
          IDL.Float64,
          IDL.Variant({ 'missed' : IDL.Null, 'delivered' : IDL.Null }),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addMilkProductionRecord' : IDL.Func(
        [Time, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getDeliveryRecordsByCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DeliveryRecord)],
        ['query'],
      ),
    'getDeliveryRecordsByDate' : IDL.Func(
        [Time],
        [IDL.Vec(DeliveryRecord)],
        ['query'],
      ),
    'getDeliveryRecordsByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DeliveryRecord)],
        ['query'],
      ),
    'getMilkProductionRecords' : IDL.Func(
        [],
        [IDL.Vec(MilkProductionRecord)],
        ['query'],
      ),
    'getMilkRecordsByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(MilkProductionRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };