/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'activeStatus' : boolean,
  'address' : string,
  'phone' : string,
}
export interface DeliveryRecord {
  'id' : bigint,
  'status' : { 'missed' : null } |
    { 'delivered' : null },
  'date' : Time,
  'quantityLiters' : number,
  'deliveryBoyName' : string,
  'notes' : string,
  'customerId' : bigint,
}
export interface MilkProductionRecord {
  'id' : bigint,
  'date' : Time,
  'quantityLiters' : number,
  'notes' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string, string, boolean], bigint>,
  'addDeliveryRecord' : ActorMethod<
    [
      bigint,
      string,
      Time,
      number,
      { 'missed' : null } |
        { 'delivered' : null },
      string,
    ],
    bigint
  >,
  'addMilkProductionRecord' : ActorMethod<[Time, number, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getDeliveryRecordsByCustomer' : ActorMethod<[bigint], Array<DeliveryRecord>>,
  'getDeliveryRecordsByDate' : ActorMethod<[Time], Array<DeliveryRecord>>,
  'getDeliveryRecordsByMonth' : ActorMethod<
    [bigint, bigint],
    Array<DeliveryRecord>
  >,
  'getMilkProductionRecords' : ActorMethod<[], Array<MilkProductionRecord>>,
  'getMilkRecordsByMonth' : ActorMethod<
    [bigint, bigint],
    Array<MilkProductionRecord>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];